language: node_js
node_js:
- 14
before_deploy:
- touch .env
- echo REACT_APP_NAME=$REACT_APP_NAME >> .env
- echo REACT_APP_VERSION=$REACT_APP_VERSION >> .env
- echo REACT_APP_URL=$REACT_APP_URL >> .env
- echo REACT_APP_TODO_API_ENDPOINT=$REACT_APP_TODO_API_ENDPOINT >> .env
- echo REACT_APP_GOOGLE_OAUTH_CLIENT_ID=$REACT_APP_GOOGLE_OAUTH_CLIENT_ID >> .env
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: qA4lMQ1ClbKvhXlQhu0ssK5CDs7sm3oeegMowiz/Y6yo53EhAEK0mdg8Jz4V75on7TCiZ9mp5XmrTxj9DI2xf8sEFRg+sSGRCHp77fmMMeIddTCbc/njtOB7+vAscskOeNqnxrKuaYkx1MI6Vk+HybwaK74GdA0zg/NX3F+mef6u9kl8GI2GLZm5wiwrnw5w8nqiiVQk+GurourasvBmefKfGo5PaDvp6BzwemGznmVjYtpfxxtkMyr8FjGv/KyJiZ/NZU2sUAwQnPRWg3WrU1/wboOE7EGw4njgSixOJDjDtUSR84z1LvXkllzCah7R9m+5hk58N7eIjTwC8XtS94pjqRcvswfZQv7KL8F8X1Lj1ZOgmCAnvpxfJeXWL79Cxi0i5MTzXEd6WwGF7wSEvZnleegqedb5Pwx0SF23v0hYtrutVhvuFQLHDJ18MeKM1OecCycqy1oL3kvzWICWyjdKD4hKbqHASeLXXEYtGPO0B9+gIytvRt1oRSI5eu4PP666F5rWkpZCrMgpIuTXcHdTykN1WPXSLO54HKxP7DP0x1CsMLX6waqf0gvK6hqWkzKqC4Yu0my4DPkrU3jnClvPosmrPoJ8M/HCm/mfsvG4lIuQGyCWcR2LtfV7CKfPaDm+ubyLQtadc2t8s2fbJYXS0E6RGE9Kth33JlzcfBI=
  on: main
  app:
    main: ardafirdausr-todo-client
