language: node_js

node_js:
- 14

before_script:
- touch .env
- echo REACT_APP_NAME=$REACT_APP_NAME >> .env
- echo REACT_APP_VERSION=$REACT_APP_VERSION >> .env
- echo REACT_APP_URL=$REACT_APP_URL >> .env
- echo REACT_APP_TODO_API_ENDPOINT=$REACT_APP_TODO_API_ENDPOINT >> .env
- echo REACT_APP_GOOGLE_OAUTH_CLIENT_ID=$REACT_APP_GOOGLE_OAUTH_CLIENT_ID >> .env

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: IRV0a/AJVcUrIrP0VvSJEWb0MsFuFi31tQThJASNfgSY7neHJv8xVTL7geWnMmg6P6L+ZOyYW3ke5cIKjtS5ZciW5i3Fie2agAUCy073qW2bioXhnN6Qut7FbKV21uKW89xE4TnM73YnCRiFqGAq6wg3UrD9UrGBWIyp49Ie9mSjeVISR46k8ChYE/tYFzT8M2Hp91ZR59+iYZ9Zzlz9isimCD21zfGZFN2DRqPoC3ccfqDEHiejp06LX71IgAW8+8p7vesiWX9GktTz2XjtzejmOtOmIMYPwj6nmJduWL7uY8M0GcAkj3l4keh1N+tP9CUZFjgV5PmRQAIWRGm9p0ESadVT4ZTIZ0/nXWxyVr3pgMl7siZaFIBHAaeTEHzUwc4A4Kh8vdUJNtuulvtcylmz78GNHkAURO+/MguqCyo4AFcIhpXoMmCKUcpQsu6uBs+JSGYHz/hO4Ub5M2SzufKW4HRA4Co2xABfsRliEPJKZdKipwSuXNuHeyCCI1dwUJTPVUyXzkqjhJTxcUurZcVv2pDPxseUHRahCGbnbrrBoRjY2tYxaR8YYI0rJ9paNRXfmGCEM1Kzozo+wWI14+C4BMD6JotJHxh5HG0WpJHgZPA88AUgvKerB35mwfO3xg8hXMSsdQ4IO5HG3qNxndFrMM0hRlyNtJdjOvIbL0w=
  on: main
  app:
    main: ardafirdausr-todo-client
